.TH "HND_STR" 3 "Thu Jun 8 2017" "Version 3.0.0" "ACP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HND_STR \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBacp_atkey_t\fP \fBxkey\fP"
.br
.ti -1c
.RI "\fBxla_t\fP * \fBxla\fP"
.br
.ti -1c
.RI "\fBacp_ga_t\fP \fBxga\fP"
.br
.ti -1c
.RI "\fBacp_ga_t\fP \fBbga\fP"
.br
.ti -1c
.RI "size_t \fBbsz\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ACP Library from the source code\&.
