.TH "lock" 3 "Thu Jun 8 2017" "Version 3.0.0" "ACP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lock \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int * \fBlockbody\fP"
.br
.ti -1c
.RI "\fBacp_atkey_t\fP \fBatkey\fP"
.br
.ti -1c
.RI "\fBprocinfo_t\fP \fBinfo\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ACP Library from the source code\&.
