.TH "msgbuf" 3 "Thu Jun 8 2017" "Version 3.0.0" "ACP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msgbuf \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBacp_list_t\fP \fBlocalbuf\fP"
.br
.ti -1c
.RI "\fBprocinfo_t\fP \fBremotebufs\fP"
.br
.ti -1c
.RI "void * \fBtmpmsg\fP"
.br
.ti -1c
.RI "\fBacp_atkey_t\fP \fBtmpmsgkey\fP"
.br
.ti -1c
.RI "\fBacp_ga_t\fP \fBtmpmsgga\fP"
.br
.ti -1c
.RI "\fBlock_t\fP \fBlock\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ACP Library from the source code\&.
