.TH "procinfo" 3 "Thu Jun 8 2017" "Version 3.0.0" "ACP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
procinfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBsb\fP"
.br
.ti -1c
.RI "int \fBnb\fP"
.br
.ti -1c
.RI "\fBacp_atkey_t\fP \fBbodykey\fP"
.br
.ti -1c
.RI "\fBacp_ga_t\fP \fBbodyga\fP"
.br
.ti -1c
.RI "\fBacp_ga_t\fP * \fBbody\fP"
.br
.ti -1c
.RI "void * \fBcachebody\fP"
.br
.ti -1c
.RI "\fBacp_ga_t\fP \fBcachega\fP"
.br
.ti -1c
.RI "int * \fBcacheblockid\fP"
.br
.ti -1c
.RI "int * \fBcachectr\fP"
.br
.ti -1c
.RI "int \fBcachesz\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ACP Library from the source code\&.
